engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true

exclude_paths:
  - "public/css/"
  - "public/js/"
  - "vendor/"
