engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - php:
      - javascript:
ratings:
  paths:
  - config/**
  - module/**
exclude_paths:
- "public/css/"
- "public/js/"
- "public/js/bootstrap.js"
- "vendor/"
