language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

install:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpcs  --standard=phpcs.xml
  - vendor/bin/phpcpd --exclude test --exclude vendor ./
  # - vendor/bin/phpunit
