language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

install:
  - cp phpunit.xml.dist phpunit.xml
  - cp config/autoload/local.php.travis config/autoload/local.php
  - mysql -u root -e 'create database things;'
  - composer self-update
  - composer install --no-interaction
  - ./vendor/bin/doctrine-module orm:schema-tool:create

script:
  - vendor/bin/phpcs  --standard=phpcs.xml -n
  - vendor/bin/phpcpd --exclude vendor ./
  - vendor/bin/phpunit
