<div class="row">
    <div class="col-md-12">
    <div id="map" style="height: 600px;" class="col-md-12"></div>
    </div>
    <script>
        function initMap() {
            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 12,
                center: {lat: 52.072, lng: 5.05}
            });

            setMarkers(map);
        }

        // Marker data that has been prepared in the controller
        <?php
        echo $markers;
        echo $gateways;
        ?>

        function setMarkers(map) {
            var image = {
                url: '<?php echo $this->basePath('img/wifi.png') ?>',
                size: new google.maps.Size(32, 32),
                origin: new google.maps.Point(0, 0),
                anchor: new google.maps.Point(16, 32)
            };
            var gatewayImage = {
                url: '<?php echo $this->basePath('img/gateway.png') ?>',
                size: new google.maps.Size(32, 32),
                origin: new google.maps.Point(0, 0),
                anchor: new google.maps.Point(16, 32)
            };
            var infowindow = new google.maps.InfoWindow();

            for (i = 0; i < sodaqMarkers.length; i++) {
                point = sodaqMarkers[i];
                marker = new google.maps.Marker({
                    position: {lat: point[1], lng: point[2]},
                    map: map,
                    icon: image,
                    title: point[0]
                });
                content = "<span>" + point[3] + ":<br>" + point[0] + "<br>" + point[1] + ";" + point[2] + "</span>";
                google.maps.event.addListener(marker,'click', (function(marker, content, infowindow){
                    return function() {
                        infowindow.setContent(content);
                        infowindow.open(map, marker);
                    };
                })(marker, content, infowindow));
            }
            for (i = 0; i < gatewayMarkers.length; i++) {
                point = gatewayMarkers[i];
                marker = new google.maps.Marker({
                    position: {lat: point[1], lng: point[2]},
                    map: map,
                    icon: gatewayImage,
                    title: point[0]
                });
                content = "<span>" + point[0] + ": " + point[1] + ";" + point[2] + "</span>";
                google.maps.event.addListener(marker,'click', (function(marker, content, infowindow){
                    return function() {
                        infowindow.setContent(content);
                        infowindow.open(map, marker);
                    };
                })(marker, content, infowindow));
            }
        }
    </script>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Messages</h3>
            </div>
            <div class="panel-body">
                <p>
                <table class="table" id="messages">
                    <thead>
                        <tr>
                            <th>Device Id</th>
                            <th>Date / Time</th>
                            <th>Date / Time Sort</th>
                            <th>Latitude / Longitude</th>
                            <th>Speed</th>
                            <th>Course</th>
                            <th>Voltage</th>
                            <th>Temperature</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php
                    foreach ($messages as $message) {
                        echo '<tr>';
                        echo '<td>' . $message->deviceId . '</td>';
                        echo '<td>';
                        echo DateTime::createFromFormat('Y-m-d\TH:i:s', substr($message->metadata->time, 0, 19))->add(new DateInterval('PT2H'))->format('d-m-Y H:i:s');
                        echo '</td>';
                        echo '<td>' . substr($message->metadata->time, 0, 19) . '</td>';
                        if (!empty($message->decodedPayload)) {
                            echo '<td>';
                            echo '<a href="http://maps.google.com/?q='
                                . $message->decodedPayload->lat . ',' . $message->decodedPayload->lon . '">'
                                . $message->decodedPayload->lat . ' / ' . $message->decodedPayload->lon . '</a>';
                            echo '</td>';
                            echo '<td>' . $message->decodedPayload->speed . '</td>';
                            echo '<td>' . $message->decodedPayload->course . '</td>';
                            echo '<td>' . $message->decodedPayload->batvolt . 'v</td>';
                            echo '<td>' . $message->decodedPayload->boardtemp . '&deg;C</td>';
                        } else {
                            echo '<td></td><td></td><td></td><td></td><td></td>';
                        }
                        echo '</tr>';
                    }

                    ?>
                    </tbody>
                </table>
                </p>
            </div>
        </div>
    </div>
</div>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=<?php echo $apiKey; ?>&callback=initMap">
</script>
<script>
$(document).ready(function(){
    $('#messages').DataTable({
        order: [[1, "desc"]],
        columns: [
            {
                data: "id",
                sortable: false
            },
            {
                data: "timestamp",
                orderData: [2]
            },
            {
                data: "timestamp_sorting",
                visible: false,
                searchable: false
            },
            {
                data: "latLon",
                sortable: false
            },
            {
                data: "speed",
                sortable: false
            },
            {
                data: "course",
                sortable: false
            },
            {
                data: "voltage",
                sortable: false
            },
            {
                data: "temperature",
                sortable: false
            }
        ]
    });
});
</script>
