<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">All requests done to the post endpoint</h3>
            </div>
            <div class="panel-body row">
                <table class="table" id="requests">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Timestamp</th>
                            <th>TimestampSort</th>
                            <th>Status</th>
                            <th>Content</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php
                    /** @var \Application\Entity\Payload $payload */
                    foreach ($payloads as $payload) {
                        echo '<tr>';
                        echo '<td>' . $payload->getId() . '</td>';
                        echo '<td>' . $payload->getDateCreated()->format('d-m-Y H:i:s') . '</td>';
                        echo '<td>' . $payload->getDateCreated()->format('Y-m-d H:i:s') . '</td>';
                        echo '<td>' . $payload->getFormattedStatus() . '</td>';
                        echo '<td>' . $payload->getContent() . '</td>';
                        echo '</tr>';
                    }

                    ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function(){
        $('#requests').DataTable({
            order: [[0, "desc"]],
            columns: [
                {
                    data: "id",
                    sortable: true
                },
                {
                    data: "timestamp",
                    orderData: [2]
                },
                {
                    data: "timestamp_sorting",
                    visible: false,
                    searchable: false
                },
                {
                    data: "status"
                },
                {
                    data: "content",
                    sortable: false,
                    render: function (data, type, row) {
                        jsonData = JSON.parse(data);
                        delete jsonData['downlink_url'];
                        return "<pre style='font-size: 8px;'>" + JSON.stringify(jsonData, undefined, 4) + "</pre>";
                    }
                }
            ]
        });
    });
</script>

