<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">All requests done to the post endpoint</h3>
            </div>
            <div class="panel-body row">
                <table class="table" id="requests">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Timestamp</th>
                            <th>Status</th>
                            <th>Content</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php
                    /** @var \Application\Entity\Payload $payload */
                    foreach ($payloads as $payload) {
                        echo '<tr>';
                        echo '<td>' . $payload->getId() . '</td>';
                        echo '<td>' . $payload->getDateCreated()->format('d-m-Y H:i:s') . '</td>';
                        echo '<td>' . $payload->getFormattedStatus() . '</td>';
                        echo '<td><font size="1">' . $payload->getContent() . '</font></td>';
                        echo '</tr>';
                    }

                    ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function(){
        $('#requests').DataTable();
    });
</script>

